# Generated by Django 6.1.1 on 2026-09-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0003_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Staff', 'Staff'), ('Manager', 'Manager'), ('Super Admin', 'Super Admin')], default='Admin', max_length=50, null=True),
        ),
    ]
